### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by NatoBoram** [Legoman99573/SpigotMC-Updater#1]
Isn't this a duplicate of [SpigotMCUpdater/SpigotMC-Updater](https://github.com/SpigotMCUpdater/SpigotMC-Updater)? Am I supposed to use the one created by the organization or this one? How do you manage them?

**Comment by NatoBoram** [comment]
I guess you can delete this repo and I'll start using the other one ^^

**Comment by Legoman99573** [comment]
Final state is Buildtools Updater Dev
